### ISSUE TITLE
doesn't work on node 11.6

### ISSUE THREAD

**Issue by huineng** [JamieMason/syncpack#15]
trying to run a command getting this

syncpack list-mismatches

```
(node:74583) UnhandledPromiseRejectionWarning: TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports.sync (/usr/local/lib/node_modules/syncpack/node_modules/dir-glob/index.js:56:9)
    at globDirs (/usr/local/lib/node_modules/syncpack/node_modules/globby/index.js:58:9)
    at getPattern (/usr/local/lib/node_modules/syncpack/node_modules/globby/index.js:61:64)
    at globTasks.reduce (/usr/local/lib/node_modules/syncpack/node_modules/globby/index.js:107:19)
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (/usr/local/lib/node_modules/syncpack/node_modules/globby/index.js:106:26)
    at Object.exports.getPackages (/usr/local/lib/node_modules/syncpack/dist/lib/get-packages.js:19:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/syncpack/dist/list-mismatches.js:56:31)
    at step (/usr/local/lib/node_modules/syncpack/dist/list-mismatches.js:32:23)
    at Object.next (/usr/local/lib/node_modules/syncpack/dist/list-mismatches.js:13:53)
```

**Comment by JamieMason** [comment]
Thanks @huineng. 
There was a regression in the `globby` dependency and I will put out a release soon.
