### ISSUE TITLE
feat(config): exit 1 when a dependency type is not found

### ISSUE THREAD

**Issue by guillempuche** [JamieMason/syncpack#234]
## Description

I run `syncpack list` on my Yarn monorepo. There's something is not good on my package.json or Syncpack.

Logs
```sh
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Cannot read properties of undefined (reading 'read')
    at file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/dist/get-package-json-files/package-json-file.js:20:81
    at Array.map (<anonymous>)
    at PackageJsonFile.getInstances (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/dist/get-package-json-files/package-json-file.js:20:49)
    at file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/dist/get-instances/index.js:9:305
    at file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/fiberRuntime.js:1303:243
    at body (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/core.js:444:17)
    at FiberRuntime.While (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/fiberRuntime.js:1021:14)
    at file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/fiberRuntime.js:1068:31
    at Object.context (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/tracer.js:73:17)
    at FiberRuntime.runLoop (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/fiberRuntime.js:1063:28) {
  name: '(FiberFailure) TypeError',
  [Symbol(effect/Runtime/FiberFailure)]: Symbol(effect/Runtime/FiberFailure),
  [Symbol(effect/Runtime/FiberFailure/Cause)]: {
    _tag: 'Die',
    defect: TypeError: Cannot read properties of undefined (reading 'read')
        at file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/dist/get-package-json-files/package-json-file.js:20:81
        at Array.map (<anonymous>)
        at PackageJsonFile.getInstances (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/dist/get-package-json-files/package-json-file.js:20:49)
        at file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/dist/get-instances/index.js:9:305
        at file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/fiberRuntime.js:1303:243
        at body (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/core.js:444:17)
        at FiberRuntime.While (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/fiberRuntime.js:1021:14)
        at file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/fiberRuntime.js:1068:31
        at Object.context (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/tracer.js:73:17)
        at FiberRuntime.runLoop (file:///Users/guillem/programacio/codi/cites/xiroi/xiroi/node_modules/syncpack/node_modules/effect/dist/esm/internal/fiberRuntime.js:1063:28)
  }
}
```

## Suggested Solution

Point where is the error.

## Help Needed

I add you, @JamieMason, to my private monorepo to check it.

**Comment by guillempuche** [comment]
Thanks Jamie!
This will be a good improvement.

**Comment by JamieMason** [comment]
Hey @guillempuche, this is pre-released in [14.0.0-alpha.7](https://github.com/JamieMason/syncpack/releases/tag/14.0.0-alpha.7).

You can see it by running:

```
npx syncpack@alpha lint --dependency-types typo
✗ dependencyType 'typo' does not match any of syncpack or your customTypes
✗ check your syncpack config file
```

But the same would happen if you had a typo in your config file.

**Comment by guillempuche** [comment]
Great!
